#pragma once
#ifndef AVL_UTILITY_SOUND_SAMPLE__
#define AVL_UTILITY_SOUND_SAMPLE__
/* Copyright 2012 Sheldon Bachstein
This file is part of the avl Library.

The avl Library is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

The avl Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the avl Library.  If not, see <http://www.gnu.org/licenses/>.
*/
/**
@file
<Autogenerated stub>
@author Sheldon Bachstein
@date Jun 17, 2012
*/



namespace avl
{
namespace utility
{
	/**
	*/
	class SoundSample
	{
	public:
		/** Full-spec constructor.
		*/
		SoundSample(const unsigned short& depth, const unsigned int frequency, const unsigned char* const data);
		
		/** Basic destructor.
		*/
		~SoundSample();
		
		/** Accesses the byte depth of the sample.
		@return The byte depth of the sample.
		*/
		const unsigned short GetByteDepth() const;
		
		/** Accesses the sampling frequency.
		@return The frequency rate of the sample.
		*/
		const unsigned int GetFrequency() const;
		
		/** Accesses the raw audio data of the sample.
		@return The raw sample data.
		*/
		const unsigned char* const GetAudioData() const;

	private:
		/// The byte depth of the sample.
		unsigned short byte_depth;
		/// The sampling frequency rate of the sample.
		unsigned int sampling_frequency;
		/// The raw sample data.
		const unsigned char* audio_data;

		/// NOT IMPLEMENTED.
		SoundSample();
		/// NOT IMPLEMENTED.
		SoundSample(const SoundSample&);
		/// NOT IMPLEMENTED.
		const SoundSample& operator=(const SoundSample&);
	};



} // utility
} // avl
#endif AVL_UTILITY_SOUND_SAMPLE__
