/* Copyright 2012 Sheldon Bachstein
This file is part of the avl Library.

The avl Library is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

The avl Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the avl Library.  If not, see <http://www.gnu.org/licenses/>.
*/
/**
@file
<Autogenerated stub>
@author Sheldon Bachstein
@date December 21, 2011
*/



#include<Windows.h>

void TestAssertComponent();
void TestBasicD3DRendererComponent(HINSTANCE);
void TestVertex2DComponent();
void TestSpriteComponent();
void TestDirectInputInputDeviceComponent(HINSTANCE);
void TestTextBoxComponent(HINSTANCE);

void BugFixing(HINSTANCE);

int CALLBACK WinMain(HINSTANCE instance, HINSTANCE prev_instance, LPSTR cmd_line, int show_cmd)
{
	//TestBasicD3DRendererComponent(instance);
	TestDirectInputInputDeviceComponent(instance);
	//TestTextBoxComponent(instance);

	

	return 0;
}



//#include<iostream>
void TestSettingsFileComponent();
//void TestTexturedQuadComponent();

//int main()
//{
//	//TestVertex2DComponent();
//	//TestSpriteComponent();
//	TestSettingsFileComponent();
//	return 0;
//}
