#ifndef <solution_upper>_<project_upper>_<component_upper>__
#define <solution_upper>_<project_upper>_<component_upper>__
/**
@file
<Autogenerated stub>
@author <author>
@date <date>
*/



namespace <solution>
{
namespace <project>
{





} // <project>
} // <solution>
#endif <solution_upper>_<project_upper>_<component_upper>__